#ifndef _ENVS_H

#define _ENVS_H

static char *sgf_environment_deprecated[] = {

    "SGF_LLVM_WHITELIST",
    "SGF_GCC_WHITELIST",
    "SGF_DEBUG_CHILD_OUTPUT",
    "SGF_DEFER_FORKSRV",
    "SGF_POST_LIBRARY",
    "SGF_PERSISTENT",
    "SGF_SAN_NO_INST",
    NULL

};

static char *sgf_environment_variables[] = {

    "SGF_ALIGNED_ALLOC", "SGF_ALLOW_TMP", "SGF_ANALYZE_HEX", "SGF_AS",
    "SGF_AUTORESUME", "SGF_AS_FORCE_INSTRUMENT", "SGF_BENCH_JUST_ONE",
    "SGF_BENCH_UNTIL_CRASH", "SGF_CAL_FAST", "SGF_CC", "SGF_CC_COMPILER",
    "SGF_CMIN_ALLOW_ANY", "SGF_CMIN_CRASHES_ONLY", "SGF_CMPLOG_ONLY_NEW",
    "SGF_CMPLOG_DEBUG", "SGF_CTX_K", "SGF_LLVM_DONTWRITEID", "SGF_PC_FILTER",
    "SGF_PC_FILTER_FILE", "SGF_CODE_END", "SGF_CODE_START",
    "SGF_COMPCOV_BINNAME", "SGF_DUMP_CYCLOMATIC_COMPLEXITY",
    "SGF_CMPLOG_MAX_LEN", "SGF_COMPCOV_LEVEL", "SGF_CRASH_EXITCODE",
    "SGF_CRASHING_SEEDS_AS_NEW_CRASH", "SGF_CUSTOM_MUTATOR_LIBRARY",
    "SGF_CUSTOM_MUTATOR_ONLY", "SGF_CUSTOM_MUTATOR_LATE_SEND",
    "SGF_CUSTOM_INFO_PROGRAM", "SGF_CUSTOM_INFO_PROGRAM_ARGV",
    "SGF_CUSTOM_INFO_PROGRAM_INPUT", "SGF_CUSTOM_INFO_OUT", "SGF_CXX",
    "SGF_CYCLE_SCHEDULES", "SGF_DEBUG", "SGF_DEBUG_CHILD", "SGF_DEBUG_GDB",
    "SGF_DEBUG_UNICORN", "SGF_DISABLE_REDUNDANT", "SGF_NO_REDUNDANT",
    "SGF_DISABLE_TRIM", "SGF_NO_TRIM", "SGF_DISABLE_LLVM_INSTRUMENTATION",
    "SGF_DONT_OPTIMIZE", "SGF_DRIVER_STDERR_DUPLICATE_FILENAME",
    "SGF_DUMB_FORKSRV", "SGF_EARLY_FORKSERVER", "SGF_ENTRYPOINT",
    "SGF_EXITPOINT", "SGF_EXIT_WHEN_DONE", "SGF_EXIT_ON_TIME",
    "SGF_EXIT_ON_SEED_ISSUES", "SGF_FAST_CAL", "SGF_FINAL_SYNC", "SGF_FORCE_UI",
    "SGF_FRIDA_DEBUG_MAPS", "SGF_FRIDA_DRIVER_NO_HOOK",
    "SGF_FRIDA_EXCLUDE_RANGES", "SGF_FRIDA_INST_CACHE_SIZE",
    "SGF_FRIDA_INST_COVERAGE_ABSOLUTE", "SGF_FRIDA_INST_COVERAGE_FILE",
    "SGF_FRIDA_INST_DEBUG_FILE", "SGF_FRIDA_INST_INSN", "SGF_FRIDA_INST_JIT",
    "SGF_FRIDA_INST_NO_CACHE", "SGF_FRIDA_INST_NO_DYNAMIC_LOAD",
    "SGF_FRIDA_INST_NO_OPTIMIZE", "SGF_FRIDA_INST_NO_PREFETCH",
    "SGF_FRIDA_INST_NO_PREFETCH_BACKPATCH", "SGF_FRIDA_INST_NO_SUPPRESS",
    "SGF_FRIDA_INST_RANGES", "SGF_FRIDA_INST_REGS_FILE", "SGF_FRIDA_INST_SEED",
    "SGF_FRIDA_INST_TRACE", "SGF_FRIDA_INST_TRACE_UNIQUE",
    "SGF_FRIDA_INST_UNSTABLE_COVERAGE_FILE", "SGF_FRIDA_JS_SCRIPT",
    "SGF_FRIDA_OUTPUT_STDOUT", "SGF_FRIDA_OUTPUT_STDERR",
    "SGF_FRIDA_PERSISTENT_ADDR", "SGF_FRIDA_PERSISTENT_CNT",
    "SGF_FRIDA_PERSISTENT_DEBUG", "SGF_FRIDA_PERSISTENT_HOOK",
    "SGF_FRIDA_PERSISTENT_RET", "SGF_FRIDA_STALKER_ADJACENT_BLOCKS",
    "SGF_FRIDA_STALKER_IC_ENTRIES", "SGF_FRIDA_STALKER_NO_BACKPATCH",
    "SGF_FRIDA_STATS_FILE", "SGF_FRIDA_STATS_INTERVAL", "SGF_FRIDA_TRACEABLE",
    "SGF_FRIDA_VERBOSE", "SGF_OLD_FORKSERVER", "SGF_OPT_LEVEL",
    "SGF_FUZZER_ARGS",  // oss-fuzz
    "SGF_FUZZER_STATS_UPDATE_INTERVAL", "SGF_GDB", "SGF_GCC_ALLOWLIST",
    "SGF_GCC_DENYLIST", "SGF_GCC_BLOCKLIST", "SGF_GCC_DISABLE_VERSION_CHECK",
    "SGF_GCC_INSTRUMENT_FILE", "SGF_GCC_OUT_OF_LINE", "SGF_GCC_SKIP_NEVERZERO",
    "SGF_GCJ", "SGF_HANG_TMOUT", "SGF_FORKSRV_INIT_TMOUT", "SGF_HARDEN",
    "SGF_I_DONT_CARE_ABOUT_MISSING_CRASHES", "SGF_IGNORE_PROBLEMS",
    "SGF_IGNORE_PROBLEMS_COVERAGE", "SGF_IGNORE_SEED_PROBLEMS",
    "SGF_IGNORE_TIMEOUTS", "SGF_IGNORE_UNKNOWN_ENVS", "SGF_IMPORT_FIRST",
    "SGF_IJON_HISTORY_LIMIT", "SGF_INPUT_LEN_MIN", "SGF_INPUT_LEN_MAX",
    "SGF_INST_LIBS", "SGF_INST_RATIO", "SGF_KEEP_TIMEOUTS", "SGF_KILL_SIGNAL",
    "SGF_FORK_SERVER_KILL_SIGNAL", "SGF_KEEP_TRACES", "SGF_KEEP_ASSEMBLY",
    "SGF_LD_HARD_FAIL", "SGF_LD_LIMIT_MB", "SGF_LD_NO_CALLOC_OVER",
    "SGF_LD_PASSTHROUGH", "SGF_REAL_LD", "SGF_LD_PRELOAD", "SGF_LD_VERBOSE",
    "SGF_LLVM_ALLOWLIST", "SGF_LLVM_DENYLIST", "SGF_LLVM_BLOCKLIST",
    "SGF_CMPLOG", "SGF_LLVM_CMPLOG", "SGF_GCC_CMPLOG", "SGF_LLVM_INSTRIM",
    "SGF_LLVM_CALLER", "SGF_LLVM_CTX", "SGF_LLVM_NO_ERROR",
    "SGF_LLVM_LTO_CALLER", "SGF_LLVM_LTO_CTX", "SGF_LLVM_LTO_CALLER_DEPTH",
    "SGF_LLVM_LTO_CTX_DEPTH", "SGF_LLVM_CALLER_DEPTH", "SGF_LLVM_CTX_DEPTH",
    "SGF_LLVM_CTX_K", "SGF_LLVM_DICT2FILE", "SGF_LLVM_DICT2FILE_NO_MAIN",
    "SGF_LLVM_DOCUMENT_IDS", "SGF_LLVM_INSTRIM_LOOPHEAD", "SGF_LLVM_INSTRUMENT",
    "SGF_LLVM_LTO_AUTODICTIONARY", "SGF_LLVM_AUTODICTIONARY",
    "SGF_LLVM_SKIPSINGLEBLOCK", "SGF_LLVM_IJON",
    // Marker: ADD_TO_INJECTIONS
    "SGF_LLVM_INJECTIONS_ALL", "SGF_LLVM_INJECTIONS_SQL",
    "SGF_LLVM_INJECTIONS_LDAP", "SGF_LLVM_INJECTIONS_XSS",
    "SGF_LLVM_INSTRIM_SKIPSINGLEBLOCK", "SGF_LLVM_LAF_SPLIT_COMPARES",
    "SGF_LLVM_LAF_SPLIT_COMPARES_BITW", "SGF_LLVM_LAF_SPLIT_FLOATS",
    "SGF_LLVM_LAF_SPLIT_SWITCHES", "SGF_LLVM_LAF_ALL",
    "SGF_LLVM_LAF_TRANSFORM_COMPARES", "SGF_LLVM_MAP_ADDR",
    "SGF_LLVM_NGRAM_SIZE", "SGF_NGRAM_SIZE", "SGF_LLVM_NO_RPATH",
    "SGF_LLVM_NOT_ZERO", "SGF_LLVM_INSTRUMENT_FILE", "SGF_LLVM_THREADSAFE_INST",
    "SGF_LLVM_SKIP_NEVERZERO", "SGF_NO_AFFINITY", "SGF_TRY_AFFINITY",
    "SGF_LLVM_LTO_DONTWRITEID", "SGF_LLVM_LTO_SKIPINIT", "SGF_LLVM_LTO_STARTID",
    "SGF_FUZZER_LOOPCOUNT", "SGF_NO_ARITH", "SGF_NO_AUTODICT", "SGF_NO_BUILTIN",
#if defined USE_COLOR && !defined ALWAYS_COLORED
    "SGF_NO_COLOR", "SGF_NO_COLOUR",
#endif
    "SGF_NO_CPU_RED", "SGF_NO_SYNC",
    "SGF_ENABLE_FEEDBACK", "SGF_CHECK_DATA_RACE", "SGF_SKELETON_GRAPH_HIGHEST_STEP", "SGF_POTENTIAL_LOCATIONS_FILE", "SGF_CUTOFF_PERCENTILE", "SGF_INTERESTING_LOCATIONS_FILE", "SGF_QUEUE_IMPL", "SGF_SC_MODE", "SGF_LOG_GRAPH_RUN_DETAILS", "SGF_COMPLETE_GRAPH_BUDGET", "SGF_CLEAR_QUEUE_AFTER_PHASES", "SGF_KEEP_ENTRIES_PER_EDGE", "SGF_MIN_PHASE_RUNS", "SGF_QUEUE_GROWTH_THRESHOLD", "DO_INTELLIGENT_SG_FUZZING",// Added by us
    "SGF_NO_CFG_FUZZING",  // sgf.rs rust crate option
    "SGF_NO_CRASH_README", "SGF_NO_FORKSRV", "SGF_NO_UI", "SGF_NO_PYTHON",
    "SGF_NO_STARTUP_CALIBRATION", "SGF_NO_WARN_INSTABILITY",
    "SGF_UNTRACER_FILE", "SGF_LLVM_USE_TRACE_PC", "SGF_MAP_SIZE", "SGF_MAPSIZE",
    "SGF_MAX_DET_EXTRAS",
    "SGF_NO_X86",  // not really an env but we dont want to warn on it
    "SGF_NOOPT", "SGF_NYX_AUX_SIZE", "SGF_NYX_DISABLE_SNAPSHOT_MODE",
    "SGF_NYX_HANDLE_INVALID_WRITE", "SGF_NYX_LOG", "SGF_NYX_REUSE_SNAPSHOT",
    "SGF_PASSTHROUGH", "SGF_PATH", "SGF_PERFORMANCE_FILE",
    "SGF_PERSISTENT_RECORD", "SGF_POST_PROCESS_KEEP_ORIGINAL", "SGF_PRELOAD",
    "SGF_TARGET_ENV", "SGF_PYTHON_MODULE", "SGF_QEMU_CUSTOM_BIN",
    "SGF_QEMU_COMPCOV", "SGF_QEMU_COMPCOV_DEBUG", "SGF_QEMU_DEBUG_MAPS",
    "SGF_QEMU_BLOCK_COV", "SGF_QEMU_DISABLE_CACHE", "SGF_QEMU_DRIVER_NO_HOOK",
    "SGF_QEMU_FORCE_DFL", "SGF_QEMU_PERSISTENT_ADDR", "SGF_QEMU_PERSISTENT_CNT",
    "SGF_QEMU_PERSISTENT_GPR", "SGF_QEMU_PERSISTENT_HOOK",
    "SGF_QEMU_PERSISTENT_MEM", "SGF_QEMU_PERSISTENT_RET",
    "SGF_QEMU_PERSISTENT_RETADDR_OFFSET", "SGF_QEMU_PERSISTENT_EXITS",
    "SGF_QEMU_INST_RANGES", "SGF_QEMU_EXCLUDE_RANGES", "SGF_QEMU_SNAPSHOT",
    "SGF_QEMU_TRACK_UNSTABLE", "SGF_QEMU_IJON", "SGF_QUIET",
    "SGF_RANDOM_ALLOC_CANARY", "SGF_REAL_PATH", "SGF_SHA1_FILENAMES",
    "SGF_SHUFFLE_QUEUE", "SGF_SKIP_BIN_CHECK", "SGF_SKIP_CPUFREQ",
    "SGF_SKIP_CRASHES", "SGF_SKIP_OSSFUZZ", "SGF_STATSD", "SGF_STATSD_HOST",
    "SGF_STATSD_PORT", "SGF_STATSD_TAGS_FLAVOR", "SGF_SYNC_TIME",
    "SGF_TESTCACHE_SIZE", "SGF_TESTCACHE_ENTRIES", "SGF_TMIN_EXACT",
    "SGF_TMPDIR", "SGF_TOKEN_FILE", "SGF_TRACE_PC", "SGF_USE_ASAN",
    "SGF_USE_MSAN", "SGF_USE_TRACE_PC", "SGF_USE_UBSAN", "SGF_UBSAN_VERBOSE",
    "SGF_USE_TSAN", "SGF_USE_CFISAN", "SGF_CFISAN_VERBOSE", "SGF_USE_LSAN",
    "SGF_WINE_PATH", "SGF_NO_SNAPSHOT", "SGF_EXPAND_HAVOC_NOW", "SGF_USE_FASAN",
    "SGF_USE_QASAN", "SGF_PRINT_FILENAMES", "SGF_PIZZA_MODE",
    "SGF_NO_FASTRESUME", "SGF_SAN_ABSTRACTION", "SGF_LLVM_ONLY_FSRV",
    "SGF_GCC_ONLY_FRSV", "SGF_SAN_RECOVER",
    "SGF_PRELOAD_DISCRIMINATE_FORKSERVER_PARENT", "SGF_FORKSRV_UID",
    "SGF_FORKSRV_GID", "SGF_COMPILER_LAUNCHER",
#ifdef __AFL_CODE_COVERAGE
    "SGF_DUMP_PC_MAP",
#endif
    NULL

};

extern char *sgf_environment_variables[];

#endif

